Cleaner logic

diff --git a/action.yaml b/action.yaml
--- a/action.yaml
+++ b/action.yaml
@@ -234,10 +234,9 @@ runs:
       - name: Format output
         if: inputs.post-result-as-comment
         run: |
-          version="${{ steps.bioccheck-version.outputs.VERSION }}"
           PR_COMMENT_HEADER="$(head -2 result.txt)"
           PR_COMMENT_SUMMARY="$(grep -A 3 "Summary" result.txt | grep -v "Summary")"
-          IS_NEW=$(R -s -e "message(compareVersion('1.32.0', '${version}'))")
+          IS_NEW=$(R -s -e "message(compareVersion('1.32.0', packageVersion('BiocCheck'))")
           if [ $IS_NEW -ge 0 ]
           then {
             PR_COMMENT_HEADER="$(head -9 result.txt)"
@@ -264,6 +263,7 @@ runs:
           \`\`\`
           ${PR_COMMENT_SUMMARY}
           \`\`\`
+          EOF
         shell: /usr/bin/bash --noprofile --norc -e {0}
 
       - uses: marocchino/sticky-pull-request-comment@v2
@@ -274,12 +274,19 @@ runs:
 
       - name: Check bioccheck status
         run: |
-          if [[ $(cat bioccheck-errors | wc -l) -gt 0 &&  "${{ inputs.allow-failure }}" == "false" ]]; then
-            echo "❌ BiocCheck has errors"
-            exit 1
-          elif [[ $(cat bioccheck-errors | wc -l) -gt 0 ]]; then
-             echo "⚠️ BiocCheck produced WARNINGs"
-          else
-            echo "💚 BiocCheck status OK"
+          error_count=$(cat bioccheck-errors | wc -l)
+          if [ $error_count -gt 0 ]
+          then {
+            if [ "${{ inputs.allow-failure }}" == "false" ]
+            then {
+              echo "❌ BiocCheck has errors"
+              exit 1
+            } else {
+              echo "⚠️ BiocCheck produced WARNINGs"
+            }
+            fi
+          } else {
+            echo "💚 No issues with BiocCheck"
+          }
           fi
         shell: bash
